In [1]:
# edit distance recursive

def edit_recursive(str1, str2):
    if len(str1) == 0:
        return len(str2)
    if len(str2) == 0:
        return len(str1)
    delta = 0 if str1[-1] == str2[-1] else 2
    return min(edit_recursive(str1[:-1], str2[:-1]) + delta, 
               edit_recursive(str1[:-1], str2) + 1,
               edit_recursive(str1, str2[:-1]) + 1)

edit_recursive("intention", "execution")

8

In [3]:
# edit distance dynamic programming version
def edit_dynamic(str1, str2):
    n, m = len(str1), len(str2)
    current_row = range(n + 1) 
    for i in range(1, m + 1):
        previous_row, current_row = current_row, [i] + [0] * n
        for j in range(1,n+1):
            add, delete, change = previous_row[j] + 1, current_row[j-1] + 1, previous_row[j-1]
            if str1[j-1] != str2[i-1]:
                change += 2
            current_row[j] = min(add, delete, change)

    return current_row[n]
edit_dynamic("intention", "execution")

8

In [18]:
# Needleman-Wunsch Algorithm
import numpy as np
penalty ={'match': 1, 'mismatch': -1, 'gap': -1}

def mch(alpha, beta):
    if alpha == beta:
        return penalty['match']
    else:
        return penalty['mismatch']

def needle_wunsch(s1, s2):
    m, n = len(s1), len(s2)
    score = np.zeros((m+1, n+1))
    
    for i in range(m+1):
        score[i][0] = penalty['gap'] * i
    for j in range(n+1):
        score[0][j] = penalty['gap'] * j

    for i in range(1, m + 1):
        for j in range(1, n + 1):
            diag = score[i-1][j-1] + mch(s1[i-1], s2[j-1])
            delete = score[i-1][j] + penalty['gap']
            insert = score[i][j-1] + penalty['gap']
            score[i][j] = max(diag, delete, insert)

    print('score matrix: \n%s\n' % score)
    align1, align2 = '', ''
    i, j = m, n
    
    while i > 0 and j > 0:
        score_current = score[i][j]
        score_diag = score[i-1][j-1]
        score_left = score[i][j-1]
        score_up = score[i-1][j]
    
        if score_current == score_diag + mch(s1[i-1], s2[j-1]):
            a1, a2 = s1[i-1], s2[j-1]
            i,j = i-1, j-1
        elif score_current == score_up + penalty['gap']:
            a1, a2 = s1[i-1], '-'
            i -= 1
        elif score_current == score_left + penalty['gap']:
            a1, a2 = '-', s2[j-1]
            j -= 1

        align1 += a1
        align2 += a2
            

    while i > 0:
        a1, a2 = s1[i-1], '-'
        align1 += a1
        align2 += a2
        i -= 1
        
    while j > 0:
        a1, a2 = '-', s2[j-1]
        align1 += a1
        align2 += a2
        j -= 1

    print(align1[::-1])
    print(align2[::-1])


needle_wunsch("intention","execution")

score matrix: 
[[ 0. -1. -2. -3. -4. -5. -6. -7. -8. -9.]
 [-1. -1. -2. -3. -4. -5. -6. -5. -6. -7.]
 [-2. -2. -2. -3. -4. -5. -6. -6. -6. -5.]
 [-3. -3. -3. -3. -4. -5. -4. -5. -6. -6.]
 [-4. -2. -3. -2. -3. -4. -5. -5. -6. -7.]
 [-5. -3. -3. -3. -3. -4. -5. -6. -6. -5.]
 [-6. -4. -4. -4. -4. -4. -3. -4. -5. -6.]
 [-7. -5. -5. -5. -5. -5. -4. -2. -3. -4.]
 [-8. -6. -6. -6. -6. -6. -5. -3. -1. -2.]
 [-9. -7. -7. -7. -7. -7. -6. -4. -2.  0.]]

inte-ntion
-execution


In [24]:
def suffix_array(str): 
     return sorted(range(len(str)), key=lambda i: str[i:]) 
    
suffix_array("banana$")

[6, 5, 3, 1, 0, 4, 2]